name: Checkmarx AST Scan Test
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master #Github Action version
        with:
          base_uri: http://demo.ast-cloud.com
          client_id: ${{ secrets.CLIENT_ID }}
          secret: ${{ secrets.SECRET }}

